// Objective-C API for talking to sift Go package.
//   gobind -lang=objc sift
//
// File is generated by gobind. Do not edit.

#ifndef __Core_H__
#define __Core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CoreArticle;

@interface CoreArticle : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull title;
@property (nonatomic) NSString* _Nonnull author;
@property (nonatomic) NSString* _Nonnull htmlContent;
@property (nonatomic) NSString* _Nonnull textContent;
@property (nonatomic) NSString* _Nonnull markdownContent;
@property (nonatomic) long length;
@property (nonatomic) NSString* _Nonnull excerpt;
@property (nonatomic) NSString* _Nonnull siteName;
@property (nonatomic) NSString* _Nonnull image;
@property (nonatomic) NSString* _Nonnull favicon;
@property (nonatomic) NSString* _Nonnull language;
@property (nonatomic) int64_t publishedAt;
@property (nonatomic) int64_t modifiedAt;
@end

FOUNDATION_EXPORT CoreArticle* _Nullable CoreExtractURLContent(NSString* _Nullable link, NSError* _Nullable* _Nullable error);

#endif
