
// Objective-C API for talking to the following Go packages
//
//	sift
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Shared_FRAMEWORK_H__
#define __Shared_FRAMEWORK_H__

#include "Core.objc.h"
#include "Universe.objc.h"

#endif
